### ISSUE TITLE
Unresolved reference: importDidAndKey

### ISSUE THREAD

**Issue by cbruguera** [walt-id/waltid-storage-kit#7]
Hello, I'm trying to build the storage kit with `./storagekit.sh build`   but getting the following error:

![Screenshot from 2023-01-06 10-31-40](https://user-images.githubusercontent.com/2256202/210945867-3fe3fde5-31a7-475c-85eb-774427b563d2.png)

The same occurs when building with docker.

Compiling with javac 19.0.1 on Ubuntu 20.04.5 LTS

**Comment by philpotisk** [comment]
Fixed in https://github.com/walt-id/waltid-storage-kit/pull/9

**Comment by cbruguera** [comment]
Thank you

**Comment by cbruguera** [comment]
@philpotisk The previously mentioned issue was fixed but build now throws an error after failing some tests:

![Screenshot from 2023-01-06 18-52-55](https://user-images.githubusercontent.com/2256202/211007510-843bc585-ebb4-4992-addb-88bf67907828.png)

**Comment by waltkb** [comment]
Should be fixed since 283875a0
